// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOW-nzKIzQOz-6MVa7TBeri-bHsjhokms',
    appId: '1:190228762737:web:02ccb42fea8aea61f44bd0',
    messagingSenderId: '190228762737',
    projectId: 'mbti-f51fe',
    authDomain: 'mbti-f51fe.firebaseapp.com',
    storageBucket: 'mbti-f51fe.firebasestorage.app',
    measurementId: 'G-QHDNLSBJVG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQvxb_GNDnxc9gvBdGITZ8k2ZsWgVGsM4',
    appId: '1:190228762737:android:761986a110cc365af44bd0',
    messagingSenderId: '190228762737',
    projectId: 'mbti-f51fe',
    storageBucket: 'mbti-f51fe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0gXMueG5Pc3i3Gayn1v5k5rDdDXpNwqI',
    appId: '1:190228762737:ios:64f4d2ec916d6a0af44bd0',
    messagingSenderId: '190228762737',
    projectId: 'mbti-f51fe',
    storageBucket: 'mbti-f51fe.firebasestorage.app',
    iosBundleId: 'com.example.mbti',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0gXMueG5Pc3i3Gayn1v5k5rDdDXpNwqI',
    appId: '1:190228762737:ios:64f4d2ec916d6a0af44bd0',
    messagingSenderId: '190228762737',
    projectId: 'mbti-f51fe',
    storageBucket: 'mbti-f51fe.firebasestorage.app',
    iosBundleId: 'com.example.mbti',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOW-nzKIzQOz-6MVa7TBeri-bHsjhokms',
    appId: '1:190228762737:web:4c582b659acbbe78f44bd0',
    messagingSenderId: '190228762737',
    projectId: 'mbti-f51fe',
    authDomain: 'mbti-f51fe.firebaseapp.com',
    storageBucket: 'mbti-f51fe.firebasestorage.app',
    measurementId: 'G-0W34W69LNZ',
  );
}
